WITH CTE AS(
select 
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun') THEN 'WEEKEND' ELSE 'BUSINESSDAY' END as DAY_TYPE,
    from 
    {{ source('demo', 'bike') }}
)

SELECT * FROM CTE 