WITH CTE AS(
select 
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
{{getdays('STARTED_AT')}} as DAY_TYPE,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
{{getseason('STARTED_AT')}} as SEASON_OF_YEAR
    from 
    {{ source('demo', 'bike') }}
)

SELECT * FROM CTE 